name: "Renogy BT"
version: "0.0.1"
slug: "renogy_bt"
description: "Renogy BT Addon for Bluetooth monitoring"
arch:
  - aarch64
url: "https://github.com/FortezzaJ/home-assistant-addons"
startup: "application"
boot: "auto"
host_network: true
devices:
  - "/dev/ttyS0:/dev/ttyS0"  # Keep for serial, if needed
services:
  - mqtt:provide
  - bluetooth:provide
options: {}
schema: {}
